"""Multi-strategy orchestration and management."""

import logging
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Dict, Optional

from ..analysis.edge_detector import EdgeOpportunity
from ..analysis.probability_calculator import FactorWeights, ProbabilityCalculator
from ..data.models import GameState, TeamStats
from ..trading.position_tracker import Position, PositionTracker
from .loader import StrategyConfig, StrategyLoader
from .rule_engine import RuleContext, RuleEngine, RuleEvaluationResult

logger = logging.getLogger(__name__)


@dataclass
class TradingSignal:
    """A trading signal generated by a strategy."""

    strategy_id: str
    game_id: str
    market_id: str
    token_id: str
    side: str  # "home" or "away"
    action: str  # "buy" or "sell"
    size: Decimal
    price: Decimal
    edge_percentage: float
    confidence: int
    opportunity: EdgeOpportunity
    rule_result: RuleEvaluationResult


@dataclass
class ExitSignal:
    """A signal to exit a position."""

    strategy_id: str
    position: Position
    reason: str


@dataclass
class CapitalAllocation:
    """Capital allocation by risk level."""

    low_risk_percent: float = 0.50  # 50% to conservative
    medium_risk_percent: float = 0.35  # 35% to medium
    high_risk_percent: float = 0.15  # 15% to aggressive

    def get_allocation(self, risk_level: str) -> float:
        """Get allocation percentage for risk level."""
        allocations = {
            "low": self.low_risk_percent,
            "medium": self.medium_risk_percent,
            "high": self.high_risk_percent,
        }
        return allocations.get(risk_level, 0.0)


class StrategyManager:
    """Manages multiple trading strategies and capital allocation.

    Responsibilities:
    - Load and manage strategy configurations
    - Evaluate opportunities against all strategies
    - Handle capital allocation by risk level
    - Resolve conflicts between strategies
    - Track strategy performance
    """

    def __init__(
        self,
        loader: Optional[StrategyLoader] = None,
        rule_engine: Optional[RuleEngine] = None,
        position_tracker: Optional[PositionTracker] = None,
        allocation: Optional[CapitalAllocation] = None,
        total_bankroll: Decimal = Decimal("1000"),
        max_portfolio_exposure: float = 0.50,  # Max fraction of bankroll bettable
        *,
        exit_stop_loss_pct_override: Optional[float] = None,
        exit_time_stop_seconds_override: Optional[int] = None,
        exit_profit_target_percent_override: Optional[float] = None,
        conflict_min_confidence: int = 7,
        kelly_multiplier_override: Optional[float] = None,
        min_position_usdc_override: Optional[float] = None,
        min_edge_strategy_overrides: Optional[Dict[str, float]] = None,
    ):
        """Initialize strategy manager.

        Args:
            loader: Strategy loader instance
            rule_engine: Rule engine instance
            position_tracker: Position tracker instance
            allocation: Capital allocation configuration (low/medium/high risk %)
            total_bankroll: Total available bankroll
            max_portfolio_exposure: Max fraction of bankroll in positions (bettable %)
            exit_stop_loss_pct_override: If set, override strategy stop-loss %% for exit
            exit_time_stop_seconds_override: If set, override strategy time stop
            exit_profit_target_percent_override: If set, take profit at this %% (overrides strategy)
            conflict_min_confidence: Take conflicting side only if confidence >= this
            kelly_multiplier_override: If set, scale strategy Kelly by this (e.g. 0.5 = half)
            min_position_usdc_override: If set, skip signal if size below this
            min_edge_strategy_overrides: Per-strategy min edge %% (e.g. {"conservative": 3.0, "aggressive": 5.0})
        """
        self._loader = loader or StrategyLoader()
        self._rule_engine = rule_engine or RuleEngine()
        self._position_tracker = position_tracker or PositionTracker()
        self._allocation = allocation or CapitalAllocation()
        self._total_bankroll = total_bankroll
        self._max_exposure = max_portfolio_exposure
        self._exit_stop_loss_pct_override = exit_stop_loss_pct_override
        self._exit_time_stop_seconds_override = exit_time_stop_seconds_override
        self._exit_profit_target_percent_override = exit_profit_target_percent_override
        self._conflict_min_confidence = conflict_min_confidence
        self._kelly_multiplier_override = kelly_multiplier_override
        self._min_position_usdc_override = min_position_usdc_override
        self._min_edge_strategy_overrides = min_edge_strategy_overrides or {}

        # Load strategies
        self._strategies: dict[str, StrategyConfig] = {}
        self._active_strategy_ids: list[str] = []

        # Performance tracking per strategy
        self._strategy_stats: dict[str, dict] = {}

    def load_strategies(self, strategy_ids: Optional[list[str]] = None) -> None:
        """Load strategies.

        Args:
            strategy_ids: Optional list of specific strategy IDs to load.
                         If None, loads all enabled strategies.
        """
        all_strategies = self._loader.load_all()

        if strategy_ids:
            self._strategies = {
                sid: s for sid, s in all_strategies.items()
                if sid in strategy_ids and s.metadata.enabled
            }
        else:
            self._strategies = {
                sid: s for sid, s in all_strategies.items()
                if s.metadata.enabled
            }

        self._active_strategy_ids = list(self._strategies.keys())

        for sid in self._active_strategy_ids:
            self._strategy_stats[sid] = {
                "signals_generated": 0,
                "trades_executed": 0,
                "wins": 0,
                "losses": 0,
                "total_pnl": Decimal("0"),
            }

        for strategy_id, min_edge in self._min_edge_strategy_overrides.items():
            strategy = self._strategies.get(strategy_id)
            if strategy is None:
                continue
            for cond in strategy.entry_rules.conditions:
                if cond.name == "minimum_edge" and cond.field == "edge_percentage":
                    cond.value = min_edge
                    logger.info(
                        f"Strategy '{strategy_id}' minimum_edge overridden to {min_edge}%"
                    )
                    break

        logger.info(f"Loaded {len(self._strategies)} strategies: {self._active_strategy_ids}")

    def get_strategy(self, strategy_id: str) -> Optional[StrategyConfig]:
        """Get strategy by ID."""
        return self._strategies.get(strategy_id)

    def evaluate_opportunity(
        self,
        game_state: GameState,
        opportunity: EdgeOpportunity,
    ) -> list[TradingSignal]:
        """Evaluate an opportunity against all active strategies.

        Args:
            game_state: Current game state
            opportunity: Edge opportunity to evaluate

        Returns:
            List of trading signals (may be empty or have multiple)
        """
        signals = []

        for strategy_id, strategy in self._strategies.items():
            # Create evaluation context
            context = RuleContext(
                game_state=game_state,
                opportunity=opportunity,
            )

            # Evaluate entry rules
            result = self._rule_engine.evaluate_entry(strategy, context)

            if result.passed:
                # Check if we can take this position
                if not self._can_take_position(strategy, opportunity.game_id):
                    logger.debug(
                        f"Strategy {strategy_id}: Rules passed but position limit reached"
                    )
                    continue

                # Calculate position size using total bankroll for Kelly
                # (so Kelly fraction produces meaningful sizes), then cap
                # by the strategy's allocated capital.
                available_capital = self._get_available_capital(strategy)
                size = self._rule_engine.calculate_position_size(
                    strategy,
                    opportunity,
                    self._total_bankroll,
                    kelly_multiplier_override=self._kelly_multiplier_override,
                    time_remaining_seconds=game_state.total_seconds_remaining,
                )
                size = min(size, available_capital)

                min_size = strategy.position_sizing.min_position_usdc
                if self._min_position_usdc_override is not None:
                    min_size = max(min_size, self._min_position_usdc_override)
                if size < Decimal(str(min_size)):
                    logger.debug(
                        f"Strategy {strategy_id}: Size too small ({size})"
                    )
                    continue

                signal = TradingSignal(
                    strategy_id=strategy_id,
                    game_id=opportunity.game_id,
                    market_id=opportunity.market_id,
                    token_id=opportunity.token_id,
                    side=opportunity.side,
                    action="buy",
                    size=size,
                    price=opportunity.market_price,
                    edge_percentage=opportunity.edge_percentage,
                    confidence=opportunity.confidence,
                    opportunity=opportunity,
                    rule_result=result,
                )
                signals.append(signal)

                self._strategy_stats[strategy_id]["signals_generated"] += 1

                logger.info(
                    f"Strategy {strategy_id} generated signal: "
                    f"{opportunity.side} {opportunity.team_abbreviation} "
                    f"edge={opportunity.edge_percentage:.1f}% size=${size}"
                )
            else:
                logger.debug(
                    f"Strategy {strategy_id} rejected: failed rules {result.failed_rules}"
                )

        # Resolve conflicts
        signals = self._resolve_conflicts(signals)

        return signals

    def evaluate_positions(
        self,
        game_state: GameState,
        price_map: dict[str, Decimal],
    ) -> list[ExitSignal]:
        """Evaluate exit conditions for all positions.

        Args:
            game_state: Current game state
            price_map: Map of token_id to current price

        Returns:
            List of exit signals
        """
        exit_signals = []

        for position in self._position_tracker.get_all_positions():
            if not position.strategy_id:
                continue

            strategy = self._strategies.get(position.strategy_id)
            if not strategy:
                continue

            current_price = price_map.get(position.token_id)
            if current_price is None:
                continue

            should_exit, reason = self._rule_engine.evaluate_exit(
                strategy,
                position,
                current_price,
                game_state.total_seconds_remaining,
                stop_loss_pct_override=self._exit_stop_loss_pct_override,
                time_stop_seconds_override=self._exit_time_stop_seconds_override,
                profit_target_percent_override=self._exit_profit_target_percent_override,
            )

            if should_exit:
                exit_signals.append(
                    ExitSignal(
                        strategy_id=position.strategy_id,
                        position=position,
                        reason=reason,
                    )
                )

                logger.info(
                    f"Exit signal for position {position.token_id}: {reason}"
                )

        return exit_signals

    def evaluate_position(
        self,
        position: Position,
        game_state: GameState,
        price_map: dict[str, Decimal],
    ) -> Optional[ExitSignal]:
        """Evaluate exit conditions for a single position with its game state.

        Args:
            position: Position to evaluate
            game_state: Game state for the market this position belongs to
            price_map: Map of token_id to current price

        Returns:
            ExitSignal if should exit, else None
        """
        if not position.strategy_id:
            return None
        strategy = self._strategies.get(position.strategy_id)
        if not strategy:
            return None
        current_price = price_map.get(position.token_id)
        if current_price is None:
            return None
        should_exit, reason = self._rule_engine.evaluate_exit(
            strategy,
            position,
            current_price,
            game_state.total_seconds_remaining,
            stop_loss_pct_override=self._exit_stop_loss_pct_override,
            time_stop_seconds_override=self._exit_time_stop_seconds_override,
            profit_target_percent_override=self._exit_profit_target_percent_override,
        )
        if not should_exit:
            return None
        logger.info(
            f"Exit signal for position {position.token_id}: {reason}"
        )
        return ExitSignal(
            strategy_id=position.strategy_id,
            position=position,
            reason=reason,
        )

    def _can_take_position(self, strategy: StrategyConfig, game_id: str) -> bool:
        """Check if we can take a new position for this strategy/game."""
        # Check strategy concurrent position limit
        strategy_positions = self._position_tracker.get_positions_by_strategy(
            strategy.id
        )
        if len(strategy_positions) >= strategy.risk_limits.max_concurrent_positions:
            return False

        # Check per-game limit
        game_positions = [
            p for p in strategy_positions
            if p.market_id.startswith(game_id)  # Assuming market_id starts with game_id
        ]
        if len(game_positions) >= strategy.risk_limits.max_position_per_game:
            return False

        # Check total exposure
        current_exposure = self._position_tracker.total_exposure()
        max_exposure = self._total_bankroll * Decimal(str(self._max_exposure))
        if current_exposure >= max_exposure:
            return False

        return True

    def _get_available_capital(self, strategy: StrategyConfig) -> Decimal:
        """Get available capital for a strategy."""
        # Get allocation for risk level
        allocation_pct = self._allocation.get_allocation(strategy.metadata.risk_level)
        allocated = self._total_bankroll * Decimal(str(allocation_pct))

        # Subtract current exposure for this strategy
        strategy_positions = self._position_tracker.get_positions_by_strategy(
            strategy.id
        )
        strategy_exposure = sum(p.notional_value for p in strategy_positions)

        available = allocated - strategy_exposure
        return max(Decimal("0"), available)

    def _resolve_conflicts(self, signals: list[TradingSignal]) -> list[TradingSignal]:
        """Resolve conflicting signals.

        If multiple strategies signal opposite directions for the same game,
        the conflict is resolved by taking the higher-confidence signal
        or skipping the trade entirely.

        Args:
            signals: List of trading signals

        Returns:
            Filtered list without conflicts
        """
        if len(signals) <= 1:
            return signals

        # Group by game
        by_game: dict[str, list[TradingSignal]] = {}
        for signal in signals:
            if signal.game_id not in by_game:
                by_game[signal.game_id] = []
            by_game[signal.game_id].append(signal)

        resolved = []
        for game_id, game_signals in by_game.items():
            # Check for opposing signals
            home_signals = [s for s in game_signals if s.side == "home"]
            away_signals = [s for s in game_signals if s.side == "away"]

            if home_signals and away_signals:
                # Conflict! Take highest confidence or skip
                all_signals = home_signals + away_signals
                best = max(all_signals, key=lambda s: s.confidence)

                if best.confidence >= self._conflict_min_confidence:
                    logger.info(
                        f"Conflict for game {game_id}: taking {best.side} "
                        f"with confidence {best.confidence}"
                    )
                    resolved.append(best)
                else:
                    logger.info(
                        f"Conflict for game {game_id}: skipping both due to "
                        f"low confidence (max: {best.confidence})"
                    )
            else:
                # No conflict
                resolved.extend(game_signals)

        return resolved

    def record_trade_result(
        self,
        strategy_id: str,
        pnl: Decimal,
        is_win: bool,
    ) -> None:
        """Record a trade result for strategy tracking.

        Args:
            strategy_id: Strategy that made the trade
            pnl: Profit/loss
            is_win: Whether trade was profitable
        """
        if strategy_id not in self._strategy_stats:
            return

        stats = self._strategy_stats[strategy_id]
        stats["trades_executed"] += 1
        stats["total_pnl"] += pnl

        if is_win:
            stats["wins"] += 1
        else:
            stats["losses"] += 1

    def get_strategy_stats(self, strategy_id: str) -> dict:
        """Get performance stats for a strategy."""
        stats = self._strategy_stats.get(strategy_id, {})

        # Calculate derived metrics
        total_trades = stats.get("trades_executed", 0)
        wins = stats.get("wins", 0)

        stats["win_rate"] = wins / total_trades if total_trades > 0 else 0.0

        return stats

    def get_all_stats(self) -> dict[str, dict]:
        """Get stats for all strategies."""
        return {
            sid: self.get_strategy_stats(sid)
            for sid in self._strategies.keys()
        }

    def update_bankroll(self, new_bankroll: Decimal) -> None:
        """Update total bankroll.

        Args:
            new_bankroll: New bankroll amount
        """
        self._total_bankroll = new_bankroll

    @property
    def active_strategies(self) -> list[str]:
        """Get list of active strategy IDs."""
        return self._active_strategy_ids
